name: meduminder
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - asset/pill-splashpage.svg
    - asset/pill2.svg
    - asset/logo-app.svg
    - asset/google.svg
